global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: node-exporter
    static_configs:
      - targets: ['192.168.1.125:9100']
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']