version: '3.0'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    ports:
      - "${PORTAINER_PORT}:9000/tcp"
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_CONFIG_DIR}/portainer:/data

  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    ports:
      - "${JELLYFIN_WEB_PORT}:8096"
      - "${JELLYFIN_LOCAL_NETWORK_DISCOVERY_PORT}:7359/udp"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - DOCKER_MODS=davvos11/jellyfin-intro-skipper-mod:latest
    volumes:
      - ${DOCKER_CONFIG_DIR}/jellyfin/config:/config
      - ${MOVIES_DIR}:/movies
      - ${TV_DIR}:/tv
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
        - LOG_LEVEL=debug
        - TZ=${TZ}
    ports:
        - "${JELLYSEER_WEB_PORT}:${JELLYSEER_WEB_PORT}"
    volumes:
        - ${DOCKER_CONFIG_DIR}/jellyseer/config:/app/config
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    restart: unless-stopped

  ## Download clients ##
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    ports:
      - "${TRANSMISSION_WEBUI_PORT}:9091"
      - "${TRANSMISSION_CONNECTION_PORT}:51413"
      - "${TRANSMISSION_CONNECTION_PORT}:51413/udp"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TRANSMISSION_WEBUI_USER=${TRANSMISSION_WEBUI_USER}
      - TRANSMISSION_WEBUI_PASS=${TRANSMISSION_WEBUI_PASS}
      - TRANSMISSION_WEBUI_PORT=${TRANSMISSION_WEBUI_PORT}
      - TRANSMISSION_MAX_RETENTION=${TRANSMISSION_MAX_RETENTION}
      - TRANSMISSION_MAX_RATIO=${TRANSMISSION_CONNECTION_PORT}
      - TRANSMISSION_CONNECTION_PORT=${TRANSMISSION_CONNECTION_PORT}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - SONARR_PORT=${SONARR_PORT}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - RADARR_PORT=${RADARR_PORT}
    volumes:
      - ${DOCKER_CONFIG_DIR}/transmission/config:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MEDIA_DIR}:/media
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    image: hotio/qbittorrent:latest
    ports:
      - "${QBITTORRENT_WEB_UI_PORT}:${QBITTORRENT_WEB_UI_PORT}"
      - "${QBITTORRENT_CONNECTION_PORT}:${QBITTORRENT_CONNECTION_PORT}"
      - "${QBITTORRENT_CONNECTION_PORT}:${QBITTORRENT_CONNECTION_PORT}/udp"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ={TZ}
      - WEBUI_PORT=${QBITTORRENT_WEB_UI_PORT}
    volumes:
      - ${DOCKER_CONFIG_DIR}qbittorrent/config:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MEDIA_DIR}:/media
    restart: unless-stopped

## aars ##

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - "${PROWLARR_PORT}:${PROWLARR_PORT}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_CONFIG_DIR}/prowlarr/config:/config
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    ports:
      - "${RADARR_PORT}:7878"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKER_CONFIG_DIR}/radarr/config:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MOVIES_DIR}:/movies
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    ports:
      - "${SONARR_PORT}:8989"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKER_CONFIG_DIR}/sonarr/config:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${TV_DIR}:/tv
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    ports:
      - "${BAZARR_PORT}:6767"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKER_CONFIG_DIR}/bazarr/config:/config
      - ${MOVIES_DIR}:/movies
      - ${TV_DIR}:/tv
    restart: unless-stopped

  heimdall:
    container_name: heimdall
    image: lscr.io/linuxserver/heimdall:latest
    ports:
      - ${HEIMDALL_PORT}:80
      - ${HEIMDALL_SSL_PORT}:443
    volumes:
      - ${DOCKER_CONFIG_DIR}/heimdall/config

## System Monitoring
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKER_CONFIG_DIR}/prometheus/config/prometheus.yml:/etc/config/prometheus.yml
      - ${DOCKER_CONFIG_DIR}/prometheus/prometheus-data:/prometheus-data
    command: "--config.file=/etc/config/prometheus.yml"
    restart: unless-stopped

  node-exporter:
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter:latest
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /:/host:ro, slave
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
    command:
      - --path.rootfs=/host
      - --collector.systemd
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "${GRAFANA_PORT}:${GRAFANA_PORT}"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ${DOCKER_CONFIG_DIR}/grafana/provisioning/datasources.yml
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "${PIHOLE_WEB_PORT}:${PIHOLE_WEB_PORT}/tcp"
      - "${PIHOLE_WEB_PORT}:${PIHOLE_WEB_PORT}/udp"
      - "67:67/udp"
      - "8484:${PIHOLE_CONNECTION_PORT}/tcp" # Mapped 8484 to 80
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_WEB_PASSWORD}
      FTLCONF_LOCAL_IPV4: ${SERVER_LAN_IP}
      PIHOLE_DNS: 1.1.1.1;1.0.0.1 #CloudFlare DNS
    volumes:
      - "${DOCKER_CONFIG_DIR}/pihole:/etc/pihole"
      - "${DOCKER_CONFIG_DIR}/dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped