version: '3.0'

services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    restart: always
    ports:
      - "${PORTAINER_PORT}:9000/tcp"
    environment:
      - TZ=${TZ}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_CONFIG_DIR}/portainer:/data

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARED_TOKEN}
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
      - VERSION=docker
    network_mode: host
    volumes:
      - ${DOCKER_CONFIG_DIR}/plex/config:/config
      - ${MOVIES_DIR}:/movies
      - ${TV_DIR}:/tv
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=Etc/UTC
    volumes:
      - ${DOCKER_CONFIG_DIR}/overseerr/config:/config
    ports:
      - ${OVERSEER_PORT}:${OVERSEER_PORT}
    restart: unless-stopped

  ## Download clients ##
  transmission:
    container_name: transmission
    image: lscr.io/linuxserver/transmission:latest
    ports:
      - "${TRANSMISSION_WEBUI_PORT}:9091"
      - "${TRANSMISSION_CONNECTION_PORT}:51413"
      - "${TRANSMISSION_CONNECTION_PORT}:51413/udp"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - TRANSMISSION_WEBUI_USER=${TRANSMISSION_WEBUI_USER}
      - TRANSMISSION_WEBUI_PASS=${TRANSMISSION_WEBUI_PASS}
      - TRANSMISSION_WEBUI_PORT=${TRANSMISSION_WEBUI_PORT}
      - TRANSMISSION_MAX_RETENTION=${TRANSMISSION_MAX_RETENTION}
      - TRANSMISSION_MAX_RATIO=${TRANSMISSION_CONNECTION_PORT}
      - TRANSMISSION_CONNECTION_PORT=${TRANSMISSION_CONNECTION_PORT}
      - SONARR_API_KEY=${SONARR_API_KEY}
      - SONARR_PORT=${SONARR_PORT}
      - RADARR_API_KEY=${RADARR_API_KEY}
      - RADARR_PORT=${RADARR_PORT}
      - PEERPORT=${TRANSMISSION_CONNECTION_PORT}
    volumes:
      - ${DOCKER_CONFIG_DIR}/transmission/config:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MEDIA_DIR}:/media
    restart: unless-stopped

  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:latest
    ports:
      - ${QBITTORRENT_WEB_UI_PORT}:${QBITTORRENT_WEB_UI_PORT}
      - ${QBITTORRENT_CONNECTION_PORT}:${QBITTORRENT_CONNECTION_PORT}
      - ${QBITTORRENT_CONNECTION_PORT}:${QBITTORRENT_CONNECTION_PORT}/udp
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ={TZ}
      - WEBUI_PORT=${QBITTORRENT_WEB_UI_PORT}
      - TORRENTING_PORT=${QBITTORRENT_CONNECTION_PORT}
    volumes:
      - ${DOCKER_CONFIG_DIR}/qbittorrent/config:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MEDIA_DIR}:/media
    restart: unless-stopped

  nzbget:
    image: ghcr.io/linuxserver/nzbget
    container_name: nzbget
    environment:
      - PUID=${PUID}
      - PGID=${PUID}
      - TZ=${TZ}
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    volumes:
      - ${DOCKER_CONFIG_DIR}/nzbget/data:/config
      - ${DOWNLOAD_DIR}:/downloads
    ports:
      - ${NZBGET_PORT}:${NZBGET_PORT}
    restart: unless-stopped

## aars ##

  prowlarr:
    container_name: prowlarr
    image: lscr.io/linuxserver/prowlarr:latest
    ports:
      - "${PROWLARR_PORT}:${PROWLARR_PORT}"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKER_CONFIG_DIR}/prowlarr/config:/config
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    ports:
      - "${RADARR_PORT}:7878"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKER_CONFIG_DIR}/radarr/config:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${MOVIES_DIR}:/movies
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    ports:
      - "${SONARR_PORT}:8989"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKER_CONFIG_DIR}/sonarr/config:/config
      - ${DOWNLOAD_DIR}:/downloads
      - ${TV_DIR}:/tv
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    restart: unless-stopped

  bazarr:
    container_name: bazarr
    image: lscr.io/linuxserver/bazarr:latest
    ports:
      - "${BAZARR_PORT}:6767"
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ${DOCKER_CONFIG_DIR}/bazarr/config:/config
      - ${MOVIES_DIR}:/movies
      - ${TV_DIR}:/tv
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "${PIHOLE_WEB_PORT}:${PIHOLE_WEB_PORT}/tcp"
      - "${PIHOLE_WEB_PORT}:${PIHOLE_WEB_PORT}/udp"
      - "67:67/udp"
      - "8484:${PIHOLE_CONNECTION_PORT}/tcp"
    environment:
      TZ: ${TZ}
      WEBPASSWORD: ${PIHOLE_WEB_PASSWORD}
      FTLCONF_LOCAL_IPV4: ${SERVER_LAN_IP}
      PIHOLE_DNS: 1.1.1.1;1.0.0.1
    volumes:
      - "${DOCKER_CONFIG_DIR}/pihole:/etc/pihole"
      - "${DOCKER_CONFIG_DIR}/dnsmasq.d:/etc/dnsmasq.d"
    restart: unless-stopped

  tautulli:
    image: ghcr.io/tautulli/tautulli
    container_name: tautulli
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${DOCKER_CONFIG_DIR}/tautulli/config:/config
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - ${TAUTULLI_PORT}:${TAUTULLI_PORT}